#pragma once
#include <windows.h>
#include "dll.h"

//声明函数指针，方便其他地方使用
Api_AddBkList pAddBkList;
Api_AddQQ pAddQQ;
Api_AdminInviteGroup pAdminInviteGroup;
Api_CreateDisGroup pCreateDisGroup;
Api_DelBkList pDelBkList;
Api_DelFriend pDelFriend;
Api_DisabledPlugin pDisabledPlugin;
Api_GetAge pGetAge;
Api_GetBkn pGetBkn;
Api_GetBkn32 pGetBkn32;
Api_GetBlogPsKey pGetBlogPsKey;
Api_GetClassRoomPsKey pGetClassRoomPsKey;
Api_GetClientkey pGetClientKey;
Api_GetCookies pGetCookies;
Api_GetDisGroupList pGetDisGroupList;
Api_GetEmail pGetEmail;
Api_GetFriendList pGetFriendList;
Api_GetGender pGetGender;
Api_GetGroupAdmin pGetGroupAdmin;
Api_GetGroupCard pGetGroupCard;
Api_GetGroupList pGetGroupList;
Api_GetGroupMemberList pGetGroupMemberList;
Api_GetGroupName pGetGroupName;
Api_GetGroupPsKey pGetGroupPskey;
Api_GetLog pGetLog;
Api_GetLongClientkey pGetLongClientKey;
Api_GetLongLdw pGetLongLdw;
Api_GetNick pGetNick;
Api_GetNotice pGetNotice;
Api_GetObjInfo pGetObjInfo;
Api_GetObjLevel pGetObjLevel;
Api_GetObjVote pGetObjVote;
Api_GetOffLineList pGetOffLineList;
Api_GetOnLineList pGetOnLineList;
Api_GetPerExp pGetPerExp;
Api_GetPicLink pGetPicLink;
Api_GetQQAge pGetQQAge;
Api_GetQQList pGetQQList;
Api_GetRInf pGetRInf;
Api_GetSign pGetSign;
Api_GetTimeStamp pGetTimeStamp;
Api_GetVer pGetVer;
Api_GetZonePsKey pGetZonePskey;
Api_GIDTransGN pGidTransGN;
Api_GNTransGID pGNTransGID;
Api_HandleEvent pHandleEvent;
Api_IfFriend pIfFriend;
Api_InviteDisGroup pInviteDisGroup;
Api_IsEnable pIsEnable;
Api_IsShutUp pIsShutUp;
Api_JoinGroup pJoinGroup;
Api_KickDisGroupMBR pKickDisGroupMBR;
Api_KickGroupMBR pKickGroupMBR;
Api_LoadPlugin pLoadPlugin;
Api_LoginQQ pLoginQQ;
Api_NoAdminInviteGroup pNoAdminInviteGroup;
Api_OffLineQQ pOffLineQQ;
Api_OutPutLog pOutPutLog;
Api_PBGroupNotic pPBGroupNotic;
Api_PBHomeWork pPBHomeWork;
Api_PBTaoTao pPBTaoTao;
Api_QuitDisGroup pQuitDisGroup;
Api_QuitGroup pQuitGroup;
Api_SendJSON pSendJSON;
Api_SendMsg pSendMsg;
Api_SendPack pSendPack;
Api_SendVoice pSendVoice;
Api_SendXML pSendXML;
Api_SessionKey pSessionKey;
Api_SetAdmin pSetAdmin;
Api_SetGroupCard pSetGroupCard;
Api_SetRInf pSetRInf;
Api_SetShieldedGroup pSetShieldedGroup;
Api_ShakeWindow pShakeWindow;
Api_ShutUP pShutUp;
Api_SignIn pSignIn;
Api_Tea加密 pTea加密;
Api_Tea解密 pTea解密;
Api_UninstallPlugin pUninstallPlugin;
Api_UpLoadPic pUpLoadPic;
Api_UpLoadVoice pUpLoadVoice;
Api_UpVote pUpVote;

Api_GetDisGroupMemberList pGetDisGroupMemberList;
Api_GetDisGroupName pGetDisGroupName;
Api_GetFriendList_B pGetFriendList_B;
Api_GetGroupList_A pGetGroupList_A;
Api_GetOnlineState pGetOnlineState;
Api_GetQidianQQFriendsList pGetQidianQQFriendsList;
Api_GetShieldedState pGetShieldedState;
Api_HandleFriendEvent pHandleFriendEvent;
Api_GetWpa pGetWpa;
Api_GetGroupMemberList_C pGetGroupMemberList_C;

BOOL Api_PluginDestory(HINSTANCE hDllInst) {
	if (hDllInst != NULL) {
		return FreeLibrary(hDllInst);
	}
	return FALSE;
}

HINSTANCE Api_PluginInit() {
	HINSTANCE hDllInst = LoadLibrary(TEXT("IRapi.dll"));
	if (NULL != hDllInst)
	{
		pAddBkList = (Api_AddBkList)GetProcAddress(hDllInst, "Api_AddBkList");
		pAddQQ = (Api_AddQQ)GetProcAddress(hDllInst, "Api_AddQQ");
		pAdminInviteGroup = (Api_AdminInviteGroup)GetProcAddress(hDllInst, "Api_AdminInviteGroup");
		pCreateDisGroup = (Api_CreateDisGroup)GetProcAddress(hDllInst, "Api_CreateDisGroup");
		pDelBkList = (Api_DelBkList)GetProcAddress(hDllInst, "Api_DelBkList");
		pDelFriend = (Api_DelFriend)GetProcAddress(hDllInst, "Api_DelFriend");
		pDisabledPlugin = (Api_DisabledPlugin)GetProcAddress(hDllInst, "Api_DisabledPlugin");
		pGetAge = (Api_GetAge)GetProcAddress(hDllInst, "Api_GetAge");
		pGetBkn = (Api_GetBkn)GetProcAddress(hDllInst, "Api_GetBkn");
		pGetBkn32 = (Api_GetBkn32)GetProcAddress(hDllInst, "Api_GetBkn32");
		pGetBlogPsKey = (Api_GetBlogPsKey)GetProcAddress(hDllInst, "Api_GetBlogPsKey");
		pGetClassRoomPsKey = (Api_GetClassRoomPsKey)GetProcAddress(hDllInst, "Api_GetClassRoomPsKey");
		pGetClientKey = (Api_GetClientkey)GetProcAddress(hDllInst, "Api_GetClientkey");
		pGetCookies = (Api_GetCookies)GetProcAddress(hDllInst, "Api_GetCookies");
		pGetDisGroupList = (Api_GetDisGroupList)GetProcAddress(hDllInst, "Api_GetDisGroupList");
		pGetEmail = (Api_GetEmail)GetProcAddress(hDllInst, "Api_GetEmail");
		pGetFriendList = (Api_GetFriendList)GetProcAddress(hDllInst, "Api_GetFriendList");
		pGetGender = (Api_GetGender)GetProcAddress(hDllInst, "Api_GetGender");
		pGetGroupAdmin = (Api_GetGroupAdmin)GetProcAddress(hDllInst, "Api_GetGroupAdmin");
		pGetGroupCard = (Api_GetGroupCard)GetProcAddress(hDllInst, "Api_GetGroupCard");
		pGetGroupList = (Api_GetGroupList)GetProcAddress(hDllInst, "Api_GetGroupList");
		pGetGroupMemberList = (Api_GetGroupMemberList)GetProcAddress(hDllInst, "Api_GetGroupMemberList");
		pGetGroupName = (Api_GetGroupName)GetProcAddress(hDllInst, "Api_GetGroupName");
		pGetGroupPskey = (Api_GetGroupPsKey)GetProcAddress(hDllInst, "Api_GetGroupPsKey");
		pGetLog = (Api_GetLog)GetProcAddress(hDllInst, "Api_GetLog");
		pGetLongClientKey = (Api_GetLongClientkey)GetProcAddress(hDllInst, "Api_GetLongClientkey");
		pGetLongLdw = (Api_GetLongLdw)GetProcAddress(hDllInst, "Api_GetLongLdw");
		pGetNick = (Api_GetNick)GetProcAddress(hDllInst, "Api_GetNick");
		pGetNotice = (Api_GetNotice)GetProcAddress(hDllInst, "Api_GetNotice");
		pGetObjInfo = (Api_GetObjInfo)GetProcAddress(hDllInst, "Api_GetObjInfo");
		pGetObjLevel = (Api_GetObjLevel)GetProcAddress(hDllInst, "Api_GetObjLevel");
		pGetObjVote = (Api_GetObjVote)GetProcAddress(hDllInst, "Api_GetObjVote");
		pGetOffLineList = (Api_GetOffLineList)GetProcAddress(hDllInst, "Api_GetOffLineList");
		pGetOnLineList = (Api_GetOnLineList)GetProcAddress(hDllInst, "Api_GetOnLineList");
		pGetPerExp = (Api_GetPerExp)GetProcAddress(hDllInst, "Api_GetPerExp");
		pGetPicLink = (Api_GetPicLink)GetProcAddress(hDllInst, "Api_GetPicLink");
		pGetQQAge = (Api_GetQQAge)GetProcAddress(hDllInst, "Api_GetQQAge");
		pGetQQList = (Api_GetQQList)GetProcAddress(hDllInst, "Api_GetQQList");
		pGetRInf = (Api_GetRInf)GetProcAddress(hDllInst, "Api_GetRInf");
		pGetSign = (Api_GetSign)GetProcAddress(hDllInst, "Api_GetSign");
		pGetTimeStamp = (Api_GetTimeStamp)GetProcAddress(hDllInst, "Api_GetTimeStamp");
		pGetVer = (Api_GetVer)GetProcAddress(hDllInst, "Api_GetVer");
		pGetZonePskey = (Api_GetZonePsKey)GetProcAddress(hDllInst, "Api_GetZonePsKey");
		pGidTransGN = (Api_GIDTransGN)GetProcAddress(hDllInst, "Api_GIDTransGN");
		pGNTransGID = (Api_GNTransGID)GetProcAddress(hDllInst, "Api_GNTransGID");
		pHandleEvent = (Api_HandleEvent)GetProcAddress(hDllInst, "Api_HandleEvent");
		pIfFriend = (Api_IfFriend)GetProcAddress(hDllInst, "Api_IfFriend");
		pInviteDisGroup = (Api_InviteDisGroup)GetProcAddress(hDllInst, "Api_InviteDisGroup");
		pIsEnable = (Api_IsEnable)GetProcAddress(hDllInst, "Api_IsEnable");
		pIsShutUp = (Api_IsShutUp)GetProcAddress(hDllInst, "Api_IsShutUp ");
		pJoinGroup = (Api_JoinGroup)GetProcAddress(hDllInst, "Api_JoinGroup");
		pKickDisGroupMBR = (Api_KickDisGroupMBR)GetProcAddress(hDllInst, "Api_KickDisGroupMBR");
		pKickGroupMBR = (Api_KickGroupMBR)GetProcAddress(hDllInst, "Api_KickGroupMBR");
		pLoadPlugin = (Api_LoadPlugin)GetProcAddress(hDllInst, "Api_LoadPlugin");
		pLoginQQ = (Api_LoginQQ)GetProcAddress(hDllInst, "Api_LoginQQ");
		pNoAdminInviteGroup = (Api_NoAdminInviteGroup)GetProcAddress(hDllInst, "Api_NoAdminInviteGroup");
		pOffLineQQ = (Api_OffLineQQ)GetProcAddress(hDllInst, "Api_OffLineQQ");
		pOutPutLog = (Api_OutPutLog)GetProcAddress(hDllInst, "Api_OutPutLog");
		pPBGroupNotic = (Api_PBGroupNotic)GetProcAddress(hDllInst, "Api_PBGroupNotic");
		pPBHomeWork = (Api_PBHomeWork)GetProcAddress(hDllInst, "Api_PBHomeWork");
		pPBTaoTao = (Api_PBTaoTao)GetProcAddress(hDllInst, "Api_PBTaoTao");
		pQuitDisGroup = (Api_QuitDisGroup)GetProcAddress(hDllInst, "Api_QuitDisGroup");
		pQuitGroup = (Api_QuitGroup)GetProcAddress(hDllInst, "Api_QuitGroup");
		pSendJSON = (Api_SendJSON)GetProcAddress(hDllInst, "Api_SendJSON");
		pSendMsg = (Api_SendMsg)GetProcAddress(hDllInst, "Api_SendMsg");
		pSendPack = (Api_SendPack)GetProcAddress(hDllInst, "Api_SendPack");
		pSendVoice = (Api_SendVoice)GetProcAddress(hDllInst, "Api_SendVoice");
		pSendXML = (Api_SendXML)GetProcAddress(hDllInst, "Api_SendXML");
		pSessionKey = (Api_SessionKey)GetProcAddress(hDllInst, "Api_SessionKey");
		pSetAdmin = (Api_SetAdmin)GetProcAddress(hDllInst, "Api_SetAdmin");
		pSetGroupCard = (Api_SetGroupCard)GetProcAddress(hDllInst, "Api_SetGroupCard");
		pSetRInf = (Api_SetRInf)GetProcAddress(hDllInst, "Api_SetRInf");
		pSetShieldedGroup = (Api_SetShieldedGroup)GetProcAddress(hDllInst, "Api_SetShieldedGroup");
		pShakeWindow = (Api_ShakeWindow)GetProcAddress(hDllInst, "Api_ShakeWindow");
		pShutUp = (Api_ShutUP)GetProcAddress(hDllInst, "Api_ShutUP");
		pSignIn = (Api_SignIn)GetProcAddress(hDllInst, "Api_SignIn");
		pTea加密 = (Api_Tea加密)GetProcAddress(hDllInst, "Api_Tea加密");
		pTea解密 = (Api_Tea解密)GetProcAddress(hDllInst, "Api_Tea解密");
		pUninstallPlugin = (Api_UninstallPlugin)GetProcAddress(hDllInst, "Api_UninstallPlugin");
		pUpLoadPic = (Api_UpLoadPic)GetProcAddress(hDllInst, "Api_UpLoadPic");
		pUpLoadVoice = (Api_UpLoadVoice)GetProcAddress(hDllInst, "Api_UpLoadVoice");
		pUpVote = (Api_UpVote)GetProcAddress(hDllInst, "Api_UpVote");

		pGetDisGroupMemberList = (Api_GetDisGroupMemberList)GetProcAddress(hDllInst, "Api_GetDisGroupMemberList");
		pGetDisGroupName = (Api_GetDisGroupName)GetProcAddress(hDllInst, "Api_GetDisGroupName");
		pGetFriendList_B = (Api_GetFriendList_B)GetProcAddress(hDllInst, "Api_GetFriendList_B");
		pGetGroupList_A = (Api_GetGroupList_A)GetProcAddress(hDllInst, "Api_GetGroupList_A");
		pGetOnlineState = (Api_GetOnlineState)GetProcAddress(hDllInst, "Api_GetOnlineState");
		pGetQidianQQFriendsList = (Api_GetQidianQQFriendsList)GetProcAddress(hDllInst, "Api_GetQidianQQFriendsList");
		pGetShieldedState = (Api_GetShieldedState)GetProcAddress(hDllInst, "Api_GetShieldedState");
		pHandleFriendEvent = (Api_HandleFriendEvent)GetProcAddress(hDllInst, "Api_HandleFriendEvent");
		pGetWpa = (Api_GetWpa)GetProcAddress(hDllInst, "Api_GetWpa");
		pGetGroupMemberList_C = (Api_GetGroupMemberList_C)GetProcAddress(hDllInst, "Api_GetGroupMemberList_C");
	}
	return hDllInst;
}
